### ISSUE TITLE
R bindings

### ISSUE THREAD

**Issue by richfitz** [seppo0010/rlite#12]
Just a note to let you know I've created bindings for [R](https://r-project.org), modelled off your other bindings code.  It's under development atm (obviously given rlite is!).

Repo is here: https://github.com/richfitz/rrlite

Thanks for making this library: I've been hanging out for someone to do this, as I can think of so many places I could use it! :rocket:

**Comment by seppo0010** [comment]
:grinning: Cool. Linked in readme.
