### ISSUE TITLE
RLite C# / .NET

### ISSUE THREAD

**Issue by mcmonkey4eva** [seppo0010/rlite#16]
Are there bindings available for rlite to C# or .NET in general?
Or a similar library capable of the same?

EDIT: Note: mono compatibility would be ideal (Mono = runs C# / .NET on Linux, mac, etc.)
EDIT2: ... though it would also need to work on Windows...

**Comment by seppo0010** [comment]
I don't think there is.

It currently does not work on Windows. I did my best in https://github.com/seppo0010/rlite/tree/win ; I got to a point where each file compiled, but I couldn't figure out how to link in Visual Studio.

**Comment by mcmonkey4eva** [comment]
It was trivial for me to get the code loaded into VS the laziest way possible - create a new VS project, add all files... boom.

... But the project references unix headers like unistd.h everywhere...

**Comment by mcmonkey4eva** [comment]
After fixing git trouble and arguing with the compiler a bit in VS,

I got it down to this error set:

![...](http://puu.sh/jEgaa.png)

**Comment by seppo0010** [comment]
@mcmonkey4eva please submit a PR on top of the windows branch with your Visual Studio file and I'll take a look. Thanks!

**Comment by mcmonkey4eva** [comment]
My file's an utter trainwreck, I was lazy in building it and thus had to reorganize files a bit to make it all work correctly. Also I was recently... discouraged from bothering with Redis at all after learning some limitations I didn't know about previously...
