### ISSUE TITLE
Key / Value sizes

### ISSUE THREAD

**Issue by cronacronis** [seppo0010/rlite#19]
Dear all,
1. What are the limitations on key/value sizes? 
2. Is there a limit on db size? 
3. Does it degrade with size growth?

**Comment by seppo0010** [comment]
The key/value size have no limit. But they are split into chunks of 1024 bytes by default.

The db size limit is 2**31 bytes.

**Comment by seppo0010** [comment]
Also, it uses btree for lookups, so it has a O(log n) running time, meaning it does degrade less than linearly the more keys there are in the database, and elements in the hashmap/set.
