### ISSUE TITLE
Hash map error with integer specifier

### ISSUE THREAD

**Issue by mannol** [seppo0010/rlite#21]
The following code:
```
// ...
rliteCommand(ctx, "HSET a f1 %d", 1);
rliteReply* rep = rliteCommand(ctx, "HMGET a f1");
assert(rep && rep->elements == 1);
```
fails with an error: ``` unknown retval 3 ```
However, if I use ```%s``` value instead of ```%d``` value, everything works correctly.

**Comment by seppo0010** [comment]
Thanks for the bug report. I'm sorry `rliteCommand` is not as polished, I used `rliteCommandArgv` mostly.

I tried to reproduce the bug and it worked just fine. I added a new test for it https://github.com/seppo0010/rlite/commit/fbfc1ae8918f08b339f26ff6e56c7d15a44d7746 . Can you see if you can make it fail?

**Comment by mannol** [comment]
Hmm, I can still reproduce it with your test code. Another interesting thought:
```
// If I add anything together with %d it works:
rliteCommand(ctx, "HSET a f1 n%d", 1); // Works
rliteReply* rep = rliteCommand(ctx, "HMGET a f1");
assert(rep && rep->elements == 1);
```
I've been using rlite for 2 days now, most of the stuff works, so I'm pretty happy with it. Thanks for the hard work!
