### ISSUE TITLE
HLEN on non-existent key returns a incorrect value

### ISSUE THREAD

**Issue by ikreymer** [seppo0010/rlite#29]
Using rlite-py:

```
>>> import hirlite
>>> r = hirlite.Rlite()
>>> r.hlen('foo')
4341476813
```

hlen should return 0 for non-existent key (https://redis.io/commands/hlen)

**Comment by seppo0010** [comment]
The bug is already fixed in rlite, but rlite-py is running an old version. I'll upload a new one now. Thanks for the report.

**Comment by seppo0010** [comment]
The new version (0.2.1) is up. Please take a look and let me know how it goes!

**Comment by ikreymer** [comment]
Yes, confirm that it's fixed, thanks!
