### ISSUE TITLE
Ignored specifier in ZADD command

### ISSUE THREAD

**Issue by mannol** [seppo0010/rlite#30]
Executing `rliteCommand(ctx, "ZADD ayy 0 %b%d", buffer, 12, 1);` ignores the first `%b` specifier so the entry only contains `1`.

However, this `rliteCommand(ctx, "ZADD ayy 0 %d%b", 1, buffer, 12);` works as expected.

**Comment by seppo0010** [comment]
Should be fixed now 7cb8c5228307a261792e993ea36dfbc80c400bb9

**Comment by mannol** [comment]
Fix confirmed. Thanks!
