### ISSUE TITLE
Operations on non-existant key result in HirliteError

### ISSUE THREAD

**Issue by ikreymer** [seppo0010/rlite#32]
A few examples, using rlite-py where behavior results in HirliteError, but shouldn't:

smembers error on non-existent key:
```
>>> hr = hirlite.Rlite()
>>> hr.smembers('no-such-key')
HirliteError('unknown retval 3',)
```
but should return `[]`

hmget error on non-existent key:
```
>>> hr = hirlite.Rlite()
>>> hr.hmget('no-such-key', '2', 'a', 'b')
```
but should return `[None, None]`

hsetnx error:
```
>>> hr = hirlite.Rlite()
>>> hr = hirlite.Rlite()
>>> hr.hsetnx('foo', 'a', 'b')
1
>>> hr.hsetnx('foo', 'a', 'b')
HirliteError('unknown retval 2',)
```
but should return `0`

**Comment by seppo0010** [comment]
Hi! Thanks for the bug report. I fixed the three issues mentioned. I saw you were using python so I uploaded hirlite-0.3.1 with the fixes. Let me know if the fix doesn't work or any other problem appears.
